-- AlterTable
ALTER TABLE "user" ADD COLUMN     "job" TEXT,
ADD COLUMN     "phoneNumber" TEXT,
ALTER COLUMN "firstName" DROP NOT NULL,
ALTER COLUMN "lastName" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL;
